# Numpy In Python is a package which is used to do scintific calculation

# Diffrence between Numpy Array And python list
    # Consumes Less Memory
    # Fast As Compared to python List
    # Convinient to use
    # List Can Diffrent Data Types as Value
    # 

# How To Create Array In Numpy

In [2]:
import numpy as np

In [8]:
arr1 = np.array([1,2,3])
print(arr1, "Type of arr1 :", type(arr1),"arr1 Dimension :", arr1.ndim)

[1 2 3] Type of arr1 : <class 'numpy.ndarray'> arr1 Dimension : 1


In [11]:
list = []
n = int(input("Enter Your Number:"))
for i in range (1,n):
        list.append(i)

arr2 = np.array(list)
print('this is an array :',arr2)
print('this is Type of arr2 :',type(arr2))
print('this is Dimension of arr2 :',arr2.ndim)

Enter Your Number: 6


this is an array : [1 2 3 4 5]
this is Type of arr2 : <class 'numpy.ndarray'>
this is Dimension of arr2 : 1


# One Dimensional Array

In [13]:
arrOne = np.array([12,45,78,95])
print('Dimesion is :', arrOne.ndim)

Dimesion is : 1


# Two Dimensional Array

In [15]:
arrTwo = np.array([[1,2,3],[4,5,6]])
print('Dimension is :', arrTwo.ndim)

Dimension is : 2


# Three Dimesional Array

In [19]:
arrThree = np.array([[[1,2,3,4,5],[1,2,3,5,6]]])
print("Dimension is :", arrThree.ndim)

Dimension is : 3


# Multi dimensional array 

In [20]:
arrMD = np.array(list,ndmin = 6)
print(arrMD, 'Dimension is :',arrMD.ndim)

[[[[[[1 2 3 4 5]]]]]] Dimension is : 6


# Special Types Of Numpy Arrays 

# Array Filled With Zeros (0)

In [33]:
arrZeros = np.zeros((1,4,5))
print(arrZeros, "dimesion is :" , arrZeros.ndim)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]] dimesion is : 3


# Array Filled With Ones (1)

In [36]:
arrOnes = np.ones((4))
print(arrOnes, "Dimension is :", arrOnes.ndim)

[1. 1. 1. 1.] Dimension is : 1


# Empty Array

In [37]:
arrEm = np.empty(3)
print(arrEm)

[7.74860419e-304 7.74860419e-304 7.74860419e-304]


# Arange Array

In [45]:
arrArn = np.arange(1,9).reshape(2,4)
print(arrArn)

[[1 2 3 4]
 [5 6 7 8]]


# Diagonal Array 

In [50]:
digArr = np.eye(6)
print(digArr)
np.fill_diagonal(digArr,8)
print(digArr)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[8. 0. 0. 0. 0. 0.]
 [0. 8. 0. 0. 0. 0.]
 [0. 0. 8. 0. 0. 0.]
 [0. 0. 0. 8. 0. 0.]
 [0. 0. 0. 0. 8. 0.]
 [0. 0. 0. 0. 0. 8.]]


# Linspace 

In [55]:
arrLin = np.linspace(1,3,num=6).reshape(3,2)
print(arrLin)

[[1.  1.4]
 [1.8 2.2]
 [2.6 3. ]]


# Numpy Array With Random Numbers 

# Rand() : It Gives Array With random value between 0 to 1 , only Positive Values

In [62]:
arrRand = np.round(np.random.rand(2,5,6),2)
print(arrRand)

[[[0.61 0.74 0.08 0.12 0.85 0.72]
  [0.04 0.34 0.51 0.92 0.82 0.76]
  [0.81 0.94 0.27 0.31 0.56 0.03]
  [0.2  0.13 0.5  0.87 0.05 0.8 ]
  [0.23 0.43 0.49 0.94 0.38 0.51]]

 [[0.94 0.1  0.63 0.02 0.05 0.22]
  [0.45 0.73 0.38 0.7  0.56 0.46]
  [0.22 0.6  0.42 0.54 0.34 0.15]
  [0.66 0.21 0.9  0.31 0.24 0.6 ]
  [0.67 0.18 0.89 0.15 0.46 0.18]]]


# Randn() : It can Give both negative and positive value Close To Zero

In [64]:
arrRandn = np.round(np.random.randn(4,2),2)
print(arrRandn)

[[ 1.12 -0.79]
 [-1.31 -0.91]
 [-2.29  1.43]
 [ 1.76  0.25]]


# Ranf() 

In [69]:
arrRandf = np.random.ranf(4)
print(arrRandf)

[0.959236   0.64679331 0.70563958 0.35728422]


# Randint()

In [75]:
arrRint = np.random.randint(5,20,5)
print(arrRint)

[ 5 17 15 18 10]
