# Data Types In Numpy

# Int Data Type

In [7]:
import numpy as np

In [9]:
var = np.array([1,2,5])
print('data type is : ', var.dtype)

data type is :  int64


# Float Data Type 

In [12]:
varF = np.array([5.2,6.5,7.2,4.5,.65])
print("data Type is :", varF.dtype)

data Type is : float64


# String Data Type 

In [13]:
varS = np.array(['s','g','h','j','t'])
print('Data Type is :', varS.dtype)

Data Type is : <U1


In [15]:
varStr = np.array(['Rajeev','Rahul','Pinky','h'])
print('data Type is :', varStr.dtype)

data Type is : <U6


In [19]:
varS2 = np.array(['s','g','h','j','t',2,5,9,8])
print('Data Type is :', varS2.dtype)

Data Type is : <U21


# Change Data Type 

In [18]:
varData =  np.array([4,2,3,5], dtype=np.str_)
print('data type is :',  varData.dtype)

data type is : <U1


# Changing Data Type As A function (Converter Function)

In [23]:
x = np.array([4,5,6])
newDt = np.float64(x)
print('Data type of x :', x.dtype)
print('Data type of newDt :', newDt.dtype)
print(x)
print(newDt)

Data type of x : int64
Data type of newDt : float64
[4 5 6]
[4. 5. 6.]


# ASTYPE() direct dtype conversion

In [24]:
x2 = np.array([4,5,6])
newX2 = x2.astype(float)
print(x2)
print(newX2)

[4 5 6]
[4. 5. 6.]


In [25]:
arr = np.array([0, 1, 0, 3, 0])
converted = arr.astype(bool)
print(converted)
print(converted.dtype)

[False  True False  True False]
bool


In [26]:
arr = np.array([10.5, 20.1, 30.9])
converted = arr.astype(int)
print(converted)
print(converted.dtype)

[10 20 30]
int64


In [27]:
arr = np.array([3, 'Rajeev', 7.5, True])
print(arr)
print(arr.dtype)

['3' 'Rajeev' '7.5' 'True']
<U32


In [28]:
arr = np.array([True, False, 1, 0])
converted = arr.astype(int)
print(converted)
print(converted.dtype)

[1 0 1 0]
int64


In [29]:
arr = np.array(['4.5', '99.99', '7', '0'])
converted = arr.astype(float)
print(converted)
print(converted.dtype)

[ 4.5  99.99  7.    0.  ]
float64
