# Shape & Reshape in Numpy

In [1]:
import numpy as np

# Shape Function

In [5]:
arr = np.array([[1,2,5,4],[1,2,3,8]])
print(arr)
print(arr.shape)

[[1 2 5 4]
 [1 2 3 8]]
(2, 4)


In [7]:
arr2 = np.array([1,2,3,5], ndmin=4)
print(arr2)
print(arr2.shape)

[[[[1 2 3 5]]]]
(1, 1, 1, 4)


In [11]:
arr3 = np.arange(2,10)
print(arr3)
print(arr3.shape)

[2 3 4 5 6 7 8 9]
(8,)


# RESHAPE Function

In [19]:
var = np.array([1,2,3,4,5,6])
print(var)
print(var.reshape(2,3))
print(var.reshape(-1))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [22]:
newArr = np.arange(1,13)
print(newArr)

reshapedNewArr = newArr.reshape(3,4)
print(reshapedNewArr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [24]:
newArr2 = np.arange(1,13)
resNewArr2 = newArr2.reshape(2,2,3)
print(resNewArr2)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [27]:
multArr = np.array([1,2,3,4,5], ndmin=12)
print(multArr)

resMultArr = multArr.reshape(-1)
print(resMultArr)

[[[[[[[[[[[[1 2 3 4 5]]]]]]]]]]]]
[1 2 3 4 5]


In [31]:
newArr3 = np.arange(1,13)
print(newArr3)

resNewArr3 = newArr3.reshape(4,-1)
res2NewArr3 = newArr3.reshape(6,-1)
print(resNewArr3)
print(res2NewArr3)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


# ARITHMETIC  OPERATION IN NUMPY

In [33]:
atArr = np.array([1,2,3,4])

arrAdd = atArr + 3
print(arrAdd)

[4 5 6 7]


In [35]:
atArr2 = np.array([1,2,3,4])
atArr3 = np.array([12,45,78,96])

arrAdd2 = atArr2 + atArr3
print(arrAdd2)

[ 13  47  81 100]


In [45]:
add1 = np.array([12,45,78,63])
add2 = np.array([12,45,78,63])

addOfArr = np.add(add1,add2)
print(addOfArr)

[ 24  90 156 126]


In [57]:
Hello = np.array([[1,2,3,4],[5,6,7,8]])
hello2 = np.array([[4,5,6,4],[4,5,6,7]])

addHello = Hello + hello2
print(addHello)

[[ 5  7  9  8]
 [ 9 11 13 15]]


# Subtraction 

In [36]:
arrArit = np.array([1,2,3,4])

subArr = arrArit - 6
print(subArr)

[-5 -4 -3 -2]


In [47]:
subOfArr = np.subtract(add1,add2)
print(subOfArr)

[0 0 0 0]


# Multipy

In [37]:
arrArit2 = np.array([1,2,3,4])

mulArr = arrArit * 6
print(mulArr)

[ 6 12 18 24]


In [48]:
mulOfArr = np.multiply(add1,add2)
print(mulOfArr)

[ 144 2025 6084 3969]


# Division

In [41]:
arrArit3 = np.array([24,36,78,96,48])

divArr = arrArit3 / 4
divArr1 = arrArit3 // 4
print(divArr)
print(divArr1)
print (divArr.dtype)
print (divArr1.dtype)

[ 6.   9.  19.5 24.  12. ]
[ 6  9 19 24 12]
float64
int64


In [49]:
divOfArr = np.divide(add1,add2)
print(divOfArr)

[1. 1. 1. 1.]


# Modulus 

In [43]:
arrArit4 = np.array([24,36,78,96,48])

modArr = arrArit4 % 4
print(modArr)

[0 0 2 0 0]


In [50]:
modOfArr = np.mod(add1,add2)
print(modOfArr)

[0 0 0 0]


# Power 

In [51]:
powOfArr = np.power(add1,add2)
print(powOfArr)

[       8916100448256  2604998672350111773                    0
 -4675932718989443137]


# Reciprocal 

In [60]:
Hello = np.array([1, 2, 4])
recHello = np.reciprocal(Hello.astype(float))  
print(recHello)

[1.   0.5  0.25]


# BASICS ARITHMETIC FUNCTIONS 

In [67]:
uniArr = np.array([4,5,6,7,8,9])

uni2dArr = np.array([[1,2,3,4],[9,5,7,8]])

# MIN FUNCTION

In [71]:
print(uniArr.min())
print(np.min(uniArr))
print(uni2dArr)
print(np.min(uni2dArr,axis=1))
print(np.min(uni2dArr,axis=0))

4
4
[[1 2 3 4]
 [9 5 7 8]]
[1 5]
[1 2 3 4]


# MAX FUNCTIONS

In [64]:
print(uniArr.max())
print(np.max(uniArr))

9
9


# ARG - Min/Max Function 

In [65]:
print(uniArr.argmin())

0


In [66]:
print(np.argmax(uniArr))

5


In [79]:
print(uni2dArr)
print(np.argmax(uni2dArr,axis=1))

[[1 2 3 4]
 [9 5 7 8]]
[3 0]


# SQRT Function

In [81]:
print(np.round(np.sqrt(uniArr),2))

[2.   2.24 2.45 2.65 2.83 3.  ]


# Sin function

In [82]:
print(np.sin(uniArr))

[-0.7568025  -0.95892427 -0.2794155   0.6569866   0.98935825  0.41211849]


# Cos function 

In [83]:
print(np.cos(uniArr))

[-0.65364362  0.28366219  0.96017029  0.75390225 -0.14550003 -0.91113026]


# Cum Sum Function 

In [85]:
print(uniArr)
print(np.cumsum(uniArr))

[4 5 6 7 8 9]
[ 4  9 15 22 30 39]
