# BROADCASTING WITH NUMPY ARRAYS

In [1]:
import numpy as np

In [7]:
uniA1 = np.array([2,4,6,8])
uniA2 = np.array([3,6,9])
uniA3 = np.array([[4],[5],[6]])

In [10]:
print(uniA1.shape, uniA2.shape,uniA3.shape)
print(uniA1)
print(uniA2)
print(uniA3)

(4,) (3,) (3, 1)
[2 4 6 8]
[3 6 9]
[[4]
 [5]
 [6]]


# Broadcasting checks the shape from right side ( It Should be same or one of them should be 1) then it will work otherwise broadcasting Fails.

# Sum of 1d and 2d Array 

In [14]:
print(np.add(uniA1,uniA3))

[[ 6  8 10 12]
 [ 7  9 11 13]
 [ 8 10 12 14]]


In [16]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([10, 20, 30])

result = a + b

print("a shape:", a.shape)
print("b shape:", b.shape)
print("Result:\n", result)

a shape: (2, 3)
b shape: (3,)
Result:
 [[11 22 33]
 [14 25 36]]


# -->> Indexing In Numpy Array

In [23]:
indexArr = np.array([[[1,2,8],[4,5,6],[7,8,9]]])
print(indexArr)
print(indexArr[0,2,1])

[[[1 2 8]
  [4 5 6]
  [7 8 9]]]
8


In [21]:
print(np.argwhere(indexArr == 8))

[[0 2 1]]


In [24]:
print(np.argwhere(indexArr == 8))

[[0 0 2]
 [0 2 1]]


In [27]:
print(np.where(indexArr == 2))

(array([0]), array([0]), array([1]))


In [28]:
print(np.where(indexArr == 8))

(array([0, 0]), array([0, 2]), array([2, 1]))


In [31]:
indexArr2 = np.array([[1,2,3],[4,5,6]])
print(indexArr2[1,0])
print(np.argwhere(indexArr2==4))
print(np.where(indexArr2==4))

4
[[1 0]]
(array([1]), array([0]))


# -->> Slicing In Numpy Array

In [41]:
slicArr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
print(slicArr[:1])


[[10 20 30]]


In [45]:
print(slicArr[1,1:])

[50 60]


In [42]:
print(slicArr[1:2])

[[40 50 60]]


In [44]:
slicingArr = np.array([1,2,3,4,5,6,7,89,9,10])
print(slicingArr[1::3])

[ 2  5 89]


# -->> Itration In Numpy Array

In [56]:
itrArr = np.array([1,2,3,4,5,6,7,8])
itrArr2 = np.array([[1,2,3,4],[5,6,7,8]])
itrArr3 = np.array([[[1,2,3,4],[5,6,7,8]]])
print(itrArr)

[1 2 3 4 5 6 7 8]


In [48]:
for val in itrArr:
    print(val);
    

1
2
3
4
5
6
7
8


In [52]:
for row in itrArr2:
    print(row)
    for val in row:
        print(val)
        for item in val:
            print(item)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4]
1
2
3
4
[5 6 7 8]
5
6
7
8


In [57]:
for val in np.nditer(itrArr3):
    print(val)

1
2
3
4
5
6
7
8


In [58]:
for idx,val in np.ndenumerate(itrArr2):
    print(f'index {idx} : {val}')

index (0, 0) : 1
index (0, 1) : 2
index (0, 2) : 3
index (0, 3) : 4
index (1, 0) : 5
index (1, 1) : 6
index (1, 2) : 7
index (1, 3) : 8
