# Diff Between Copy & View

In [1]:
import numpy as np


# Copy

In [4]:
uniArr = np.array([1,2,4,5,6])
uaCopy = np.copy(uniArr);
uaC = uniArr.copy()
print('UniAar :',uniArr);
print('uaCopy :',uaCopy);
print('uaC :',uaC);

UniAar : [1 2 4 5 6]
uaCopy : [1 2 4 5 6]
uaC : [1 2 4 5 6]


In [5]:
viewArr = uniArr.view()
print('view :', viewArr)

view : [1 2 4 5 6]


# Diffrence Between Copy & View Is 
# --> Copy Owns The Data Views Don't,
# --> It Generates new Array Views Don't,
# --> Changes Made in Copy does Not reflect in original array , but if we make change in views it reflects in original array

# -----------------------------------------------------------------------------------

# Joins And Split 

In [7]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4,5,6])



# Joins

In [9]:
joinArr = np.concatenate((var1,var2))
print(joinArr)

[1 2 3 4 1 2 3 4 5 6]


In [18]:
var3 = np.array([[1,2,3],[4,5,6]])
var4 = np.array([[7,8,9],[10,20,30]])

joinArr2 = np.concatenate((var3,var4), axis=1)
print(var3)
print('---------------------------')
print(var4)
print('---------------------------')
print(joinArr2)


[[1 2 3]
 [4 5 6]]
---------------------------
[[ 7  8  9]
 [10 20 30]]
---------------------------
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 20 30]]


# Using Stack

In [22]:
stArr = np.stack((var3,var4), axis=1)
print(var3)
print('---------------------------')
print(var4)
print('---------------------------')
print(stArr)
print(stArr.shape)

[[1 2 3]
 [4 5 6]]
---------------------------
[[ 7  8  9]
 [10 20 30]]
---------------------------
[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 20 30]]]
(2, 2, 3)


# usng hstack

In [28]:
stArr2 = np.hstack((var3,var4))
print(var3)
print('---------------------------')
print(var4)
print('---------------------------')
print(stArr2)
print(stArr2.shape)

[[1 2 3]
 [4 5 6]]
---------------------------
[[ 7  8  9]
 [10 20 30]]
---------------------------
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 20 30]]
(2, 6)


# Using Vstack

In [27]:
stArr3 = np.vstack((var3,var4))
print(var3)
print('---------------------------')
print(var4)
print('---------------------------')
print(stArr3)
print(stArr3.shape)

[[1 2 3]
 [4 5 6]]
---------------------------
[[ 7  8  9]
 [10 20 30]]
---------------------------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 20 30]]
(4, 3)


# Split Array 

In [32]:
spArr = np.array([4,5,6,7])

newSp = np.split(spArr,2)
print(newSp, type(newSp))

[array([4, 5]), array([6, 7])] <class 'list'>


In [39]:
spArr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

newSp2 = np.split(spArr2,5, axis=1)
print(newSp2, type(newSp2))

[array([[1],
       [6]]), array([[2],
       [7]]), array([[3],
       [8]]), array([[4],
       [9]]), array([[ 5],
       [10]])] <class 'list'>


In [40]:
newSp3 = np.array_split(spArr2,4)
print(newSp3)

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]]), array([], shape=(0, 5), dtype=int64), array([], shape=(0, 5), dtype=int64)]
