# Function In Numpy Array


# Search Function : Search An array for a certain value , and return the indexes that get a match

In [1]:
import numpy as np

# np.Where()

In [2]:
sArr = np.array([1,2,3,4,5])

x = np.where( sArr == 2)
print(x)

(array([1]),)


 # np.searchsorted()

In [9]:
import numpy as np

sArr2 = np.array([8, 4, 5, 7, 9, 6, 1, 2, 4])

for idx, val in np.ndenumerate(sArr2):
    print(f'index {idx} : {val}')

sArr2.sort()  # sort it first
print("Sorted array:", sArr2)

y = np.searchsorted(sArr2, 8)  # now search in sorted array
print("Index to insert 8:", y)


index (0,) : 8
index (1,) : 4
index (2,) : 5
index (3,) : 7
index (4,) : 9
index (5,) : 6
index (6,) : 1
index (7,) : 2
index (8,) : 4
Sorted array: [1 2 4 4 5 6 7 8 9]
Index to insert 8: 7


# Bloolean search

In [10]:
print(sArr2[sArr2>4])

[5 6 7 8 9]


# Sorted Array 

In [11]:
print(np.sort(sArr2))

[1 2 4 4 5 6 7 8 9]


In [12]:
strArr = np.array(['s','d','r','g','t','d','u'])
print(np.sort(strArr))

['d' 'd' 'g' 'r' 's' 't' 'u']


# Filter Function

In [14]:
fArr = np.array([2,4,5,6,8,9,7,3,12,14,16])
fliterFun = fArr%2==0
filtered = fArr[fliterFun]
print(filtered)

[ 2  4  6  8 12 14 16]


# -----------------------------------

# Arithmatic Function In Numpy Array

# Shuffle()

In [16]:
uniArr = np.array([1,2,3,4,5])
np.random.shuffle(uniArr)
print(uniArr)

[2 4 5 3 1]


# unique()

In [18]:
uniArr2 = np.array([4,2,1,4,2,3,5,1,6,7,8,5,9])
x = np.unique(uniArr2, return_counts=True)
print(x)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([2, 2, 1, 2, 2, 1, 1, 1, 1]))


# Ressize ()

In [21]:
uniArr3 = np.array([1,2,3,4,5,6,7,8])
y = np.resize(uniArr3,(2,4))
print(y)
print('--------------')
print(uniArr3)

[[1 2 3 4]
 [5 6 7 8]]
--------------
[1 2 3 4 5 6 7 8]


# flatten ()

In [26]:
fArr = np.array([[1,2,3,4],[5,6,7,8]])
flattenArr = fArr.flatten()
print(flattenArr)
flattenArr[0]=180
print(flattenArr)
print(fArr)

[1 2 3 4 5 6 7 8]
[180   2   3   4   5   6   7   8]
[[1 2 3 4]
 [5 6 7 8]]


# Ravel ()

In [28]:
rArr = np.array([[1,2,3,4],[5,6,7,8]])
ravelArr = rArr.ravel()
print(ravelArr)
ravelArr[0]=180
print(ravelArr)
print(rArr)

[1 2 3 4 5 6 7 8]
[180   2   3   4   5   6   7   8]
[[180   2   3   4]
 [  5   6   7   8]]


# Insert ()

In [32]:
inArr = np.array([1,2,3,4,5,6,7,8,9])
a = np.insert(inArr,3,25)
b = np.insert(inArr,9,(10,11,12))
print(a)
print(b)

[ 1  2  3 25  4  5  6  7  8  9]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [37]:
inArr2 = np.array([[1,2,3],[4,5,6]])

c = np.insert(inArr2,2,18, axis=0)
print(c)

[[ 1  2  3]
 [ 4  5  6]
 [18 18 18]]


# Delete ()

In [38]:
delArr= np.array([1,2,3,4,5,6,7,8,9])

d = np.delete(delArr,4)
print(d)

[1 2 3 4 6 7 8 9]
