# MATRIX IN NUMPY

In [1]:
import numpy as np

In [10]:
var = np.matrix([[1,2,3,4,5],[6,7,8,9,10]])
var1 = np.matrix([[1,2,3,4,5],[6,7,8,9,10]])

# While multiplying matrix no. of columns in first matrix should be equal to number of rows in second matrix

In [7]:
var2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
var3 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np.multiply(var2,var3))

[[  1   4   9  16  25]
 [ 36  49  64  81 100]]


# Matrix Function

# Transpose

In [9]:
print(var * var1.T)

[[ 55 130]
 [130 330]]


# Swapaxes

In [11]:
print(np.swapaxes(var,0,1))

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [14]:
varS = np.matrix([[1,2],[3,4]])
print(varS)
print('.........')
print(np.swapaxes(varS,1,0))

[[1 2]
 [3 4]]
.........
[[1 3]
 [2 4]]


# Inverse

In [16]:
invar = np.matrix([[1,2],[3,4]])
print(np.linalg.inv(invar))

[[-2.   1. ]
 [ 1.5 -0.5]]


# Power

In [18]:
pvar = np.matrix([[1,2],[3,4]])
print(np.linalg.matrix_power(pvar,3))
print(np.linalg.matrix_power(pvar,0))
print(np.linalg.matrix_power(pvar,-2))

[[ 37  54]
 [ 81 118]]
[[1 0]
 [0 1]]
[[ 5.5  -2.5 ]
 [-3.75  1.75]]


# Determinate

In [20]:
dvar = np.matrix([[1,2],[3,4]])

print(np.linalg.det(dvar))

-2.0000000000000004
